# Generated by Django 4.1.5 on 2023-03-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='api.category'),
            preserve_default=False,
        ),
    ]
